name: app
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r-shiny=1.2.0
  - r-shinythemes=1.1.1
  - r-shinyjs=1.0
  - r-dt=0.4
  - r-purrr=0.2.5
  - r-tidyr=0.8.1
  - r-stringr=1.3.1
  - r-readr=1.3.0
  - r-dplyr=0.7.8
  - bioconductor-biostrings=2.48.0
